#!/bin/bash

rm *.class
javac *.java

echo "Running network"
java -ea Network $1

echo "Graphing 3" 
python GraphPlotter.py "data_3-3.csv" 3 > /dev/null

echo "Graphing 5"
python GraphPlotter.py "data_3-5.csv" 5 > /dev/null

echo "Graphing 7"
python GraphPlotter.py "data_3-7.csv" 7 > /dev/null

open *.png