public enum State {
	EAGER_TO_SEND,
	PREPARING_NEXT_PACKET,
	WAITING_FOR_BACK_OFF,
	TRANSMITTING_PACKET_PREAMBLE,
	TRANSMITTING_PACKET_CONTENTS,
	TRANSMITTING_JAMMING_SIGNAL,
	RECEIVER_BUSY,
	RECEIVER_IDLE,
	WAITING_INTER_PACKET_GAP;

	public boolean isTransmittingState() {
		return this == TRANSMITTING_PACKET_PREAMBLE ||
			   this == TRANSMITTING_PACKET_CONTENTS ||
			   this == TRANSMITTING_JAMMING_SIGNAL;
	}
}
