public enum State {
	UNINITIALIZED,
	EAGER_TO_SEND,
	PREPARING_NEXT_PACKET,
	WAITING_FOR_BACKOFF,
	TRANSMITTING_PACKET_PREAMBLE,
	TRANSMITTING_PACKET_CONTENTS,
	TRANSMITTING_JAMMING_SIGNAL,
	WAITING_INTERPACKET_GAP;

	public boolean isTransmittingState() {
		return this == TRANSMITTING_PACKET_PREAMBLE ||
			   this == TRANSMITTING_PACKET_CONTENTS ||
			   this == TRANSMITTING_JAMMING_SIGNAL;
	}
}
